'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TranslatedStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConnectMyPrinterRemoteFileHelper.TranslatedStrings", GetType(TranslatedStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es ist bereits ein oder mehrere Drucker in der Konfiguration vorhanden. Drucker überschreiben? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PrinterAlreadyAddedStr() As String
            Get
                Return ResourceManager.GetString("PrinterAlreadyAddedStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Diese Funktion ist in der Einstellungsdatei clientseitig nicht aktiviert. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PrinterPushFeatureNotEnabledStr() As String
            Get
                Return ResourceManager.GetString("PrinterPushFeatureNotEnabledStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Profildatei konnte nicht auf Client  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProfilePublishedFailStr1() As String
            Get
                Return ResourceManager.GetString("ProfilePublishedFailStr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  geschrieben werden. Bitte Hostname überprüfen. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProfilePublishedFailStr2() As String
            Get
                Return ResourceManager.GetString("ProfilePublishedFailStr2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Profildatei erfolgreich auf Client  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProfilePublishedSuccessStr1() As String
            Get
                Return ResourceManager.GetString("ProfilePublishedSuccessStr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  veröffentlicht. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProfilePublishedSuccessStr2() As String
            Get
                Return ResourceManager.GetString("ProfilePublishedSuccessStr2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckerprofil ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SendPrinterProfileNameStr() As String
            Get
                Return ResourceManager.GetString("SendPrinterProfileNameStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property trenn() As String
            Get
                Return ResourceManager.GetString("trenn", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
