'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TranslatedStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConnectMyPrinterAppSettingsSetup.TranslatedStrings", GetType(TranslatedStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ändere ACLs für Einstellungsdatei... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChangeACLsAtAppSettingsFileStr() As String
            Get
                Return ResourceManager.GetString("ChangeACLsAtAppSettingsFileStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungsdatei konnte nicht kopiert werden. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CopyFileToProgramPathErrorStr() As String
            Get
                Return ResourceManager.GetString("CopyFileToProgramPathErrorStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungsdatei von C:\Temp nach C:\Program Files\Michael Kirgus\ConnectMyPrinter.NET kopiert. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CopyFileToProgramPathFinishedStr() As String
            Get
                Return ResourceManager.GetString("CopyFileToProgramPathFinishedStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kopiere Einstellungsdatei von C:\Temp nach C:\Program Files\Michael Kirgus\ConnectMyPrinter.NET... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CopyFileToProgramPathStr() As String
            Get
                Return ResourceManager.GetString("CopyFileToProgramPathStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das benutzerdefinierte Logo konnte nicht kopiert werden. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CopyPictureLogoToProgramPathErrorStr() As String
            Get
                Return ResourceManager.GetString("CopyPictureLogoToProgramPathErrorStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Logo erfolgreich kopiert. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CopyPictureLogoToProgramPathFinishedStr() As String
            Get
                Return ResourceManager.GetString("CopyPictureLogoToProgramPathFinishedStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kopiere benutzerdefiniertes Logo in Anwendungsverzeichnis... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CopyPictureLogoToProgramPathStr() As String
            Get
                Return ResourceManager.GetString("CopyPictureLogoToProgramPathStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fertig. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FinishedStr() As String
            Get
                Return ResourceManager.GetString("FinishedStr", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
