'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TranslatedStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConnectMyPrinterTrayApp.TranslatedStrings", GetType(TranslatedStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckerumgebung sichern... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BackupPrintingEnv() As String
            Get
                Return ResourceManager.GetString("BackupPrintingEnv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Standardeinstellungen... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefaultSettingsEntry() As String
            Get
                Return ResourceManager.GetString("DefaultSettingsEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker trennen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DisconnectPrinterEntry() As String
            Get
                Return ResourceManager.GetString("DisconnectPrinterEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExitEntry() As String
            Get
                Return ResourceManager.GetString("ExitEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker verwalten... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LaunchAppEntry() As String
            Get
                Return ResourceManager.GetString("LaunchAppEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gerätewebseite öffnen... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OpenDeviceWebsiteEntry() As String
            Get
                Return ResourceManager.GetString("OpenDeviceWebsiteEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Anweudng kann die aktuell installierten Drucker nicht ermitteln, da die Windows-Druckerwarteschlange nicht gestartet ist. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PrintSpoolerServiceNotRunningMsgBoxMessage() As String
            Get
                Return ResourceManager.GetString("PrintSpoolerServiceNotRunningMsgBoxMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht aktualisieren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RefreshView() As String
            Get
                Return ResourceManager.GetString("RefreshView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker löschen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RemoveLocalPrinterEntry() As String
            Get
                Return ResourceManager.GetString("RemoveLocalPrinterEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckerwarteschlange neu starten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RestartPrinterQ() As String
            Get
                Return ResourceManager.GetString("RestartPrinterQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ConnectMyPrinter.NET - Drucker ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TrayIconText() As String
            Get
                Return ResourceManager.GetString("TrayIconText", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
