'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TranslatedStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConnectMyPrinterBackupApp.TranslatedStrings", GetType(TranslatedStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Möchten Sie zusätzlich die Druckereinstellungen exportieren? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportPrinterSettingsMessageStr() As String
            Get
                Return ResourceManager.GetString("ExportPrinterSettingsMessageStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es konnten keine Drucker gefunden werden, welche in einer Profildatei gespeichert werden könnten. Bitte beachten Sie, dass keine lokalen Drucker gesichert werden können. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoPrinterToSaveFoundStr() As String
            Get
                Return ResourceManager.GetString("NoPrinterToSaveFoundStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Drucker konnten nicht in eine Profildatei gesichert werden! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PrinterSavingFailStr() As String
            Get
                Return ResourceManager.GetString("PrinterSavingFailStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Drucker werden mit einem Doppelklick auf die Profildatei automatisch verbunden. Anzahl der gespeicherten Drucker:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PrinterSavingFinishedStr() As String
            Get
                Return ResourceManager.GetString("PrinterSavingFinishedStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Druckerumgebung wurde gesichert. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PrintingEnvSaveFinishedTextStr() As String
            Get
                Return ResourceManager.GetString("PrintingEnvSaveFinishedTextStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Druckerumgebung wird gesichert, bitte warten... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PrintingEnvSaveTextStr() As String
            Get
                Return ResourceManager.GetString("PrintingEnvSaveTextStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckerumgebung sichern ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PrintingEnvSaveTitleStr() As String
            Get
                Return ResourceManager.GetString("PrintingEnvSaveTitleStr", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
