'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Form1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConnectMyPrinter.NET.Form1", GetType(Form1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.AnchorStyles ähnlich wie Top, Bottom, Left, Right.
        '''</summary>
        Public Shared ReadOnly Property AdditionalInfoRTF_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("AdditionalInfoRTF.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=23,Y=172}.
        '''</summary>
        Public Shared ReadOnly Property AdditionalInfoRTF_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("AdditionalInfoRTF.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=425, Height=426}.
        '''</summary>
        Public Shared ReadOnly Property AdditionalInfoRTF_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("AdditionalInfoRTF.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 19.
        '''</summary>
        Public Shared ReadOnly Property AdditionalInfoRTF_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("AdditionalInfoRTF.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AdditionalInfoRTF_Text() As String
            Get
                Return ResourceManager.GetString("AdditionalInfoRTF.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=311, Height=22}.
        '''</summary>
        Public Shared ReadOnly Property AnwendungseinstellungenBearbeitenAdminToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("AnwendungseinstellungenBearbeitenAdminToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anwendungseinstellungen bearbeiten (Admin)... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AnwendungseinstellungenBearbeitenAdminToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("AnwendungseinstellungenBearbeitenAdminToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=311, Height=22}.
        '''</summary>
        Public Shared ReadOnly Property AnwendungseinstellungenBearbeitenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("AnwendungseinstellungenBearbeitenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anwendungseinstellungen bearbeiten... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AnwendungseinstellungenBearbeitenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("AnwendungseinstellungenBearbeitenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Möchten Sie den Drucker  ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AskUserForPrinterConnectionPart1() As String
            Get
                Return ResourceManager.GetString("AskUserForPrinterConnectionPart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  verbinden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AskUserForPrinterConnectionPart2() As String
            Get
                Return ResourceManager.GetString("AskUserForPrinterConnectionPart2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.FlatStyle ähnlich wie Flat.
        '''</summary>
        Public Shared ReadOnly Property Button1_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("Button1.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=367,Y=5}.
        '''</summary>
        Public Shared ReadOnly Property Button1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Button1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=24, Height=21}.
        '''</summary>
        Public Shared ReadOnly Property Button1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Button1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 9.
        '''</summary>
        Public Shared ReadOnly Property Button1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Button1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anwendungsinformationen/Lizenz anzeigen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Button1_ToolTip() As String
            Get
                Return ResourceManager.GetString("Button1.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.FlatStyle ähnlich wie Flat.
        '''</summary>
        Public Shared ReadOnly Property Button2_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("Button2.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=389,Y=5}.
        '''</summary>
        Public Shared ReadOnly Property Button2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Button2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=24, Height=21}.
        '''</summary>
        Public Shared ReadOnly Property Button2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Button2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 10.
        '''</summary>
        Public Shared ReadOnly Property Button2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Button2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anwendungseinstellungen/Administratoreinstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Button2_ToolTip() As String
            Get
                Return ResourceManager.GetString("Button2.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.FlatStyle ähnlich wie Flat.
        '''</summary>
        Public Shared ReadOnly Property Button3_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("Button3.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=423,Y=173}.
        '''</summary>
        Public Shared ReadOnly Property Button3_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Button3.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=22, Height=21}.
        '''</summary>
        Public Shared ReadOnly Property Button3_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Button3.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 15.
        '''</summary>
        Public Shared ReadOnly Property Button3_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Button3.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ansicht aktualisieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Button3_ToolTip() As String
            Get
                Return ResourceManager.GetString("Button3.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.FlatStyle ähnlich wie Flat.
        '''</summary>
        Public Shared ReadOnly Property Button4_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("Button4.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=346,Y=5}.
        '''</summary>
        Public Shared ReadOnly Property Button4_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Button4.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=24, Height=21}.
        '''</summary>
        Public Shared ReadOnly Property Button4_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Button4.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 17.
        '''</summary>
        Public Shared ReadOnly Property Button4_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Button4.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckerwarteschlange neu starten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Button4_ToolTip() As String
            Get
                Return ResourceManager.GetString("Button4.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property Button4_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Button4.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property Button5_Enabled() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Button5.Enabled", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.FlatStyle ähnlich wie Flat.
        '''</summary>
        Public Shared ReadOnly Property Button5_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("Button5.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.ImeMode ähnlich wie NoControl.
        '''</summary>
        Public Shared ReadOnly Property Button5_ImeMode() As System.Windows.Forms.ImeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("Button5.ImeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.ImeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=324,Y=5}.
        '''</summary>
        Public Shared ReadOnly Property Button5_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Button5.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=24, Height=21}.
        '''</summary>
        Public Shared ReadOnly Property Button5_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Button5.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 18.
        '''</summary>
        Public Shared ReadOnly Property Button5_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Button5.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle gefundenen Drucker anzeigen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Button5_ToolTip() As String
            Get
                Return ResourceManager.GetString("Button5.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property Button5_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Button5.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 23.
        '''</summary>
        Public Shared ReadOnly Property ComboBox1_ItemHeight() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ComboBox1.ItemHeight", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=23,Y=93}.
        '''</summary>
        Public Shared ReadOnly Property ComboBox1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ComboBox1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=298, Height=29}.
        '''</summary>
        Public Shared ReadOnly Property ComboBox1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ComboBox1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 0.
        '''</summary>
        Public Shared ReadOnly Property ComboBox1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ComboBox1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=312, Height=136}.
        '''</summary>
        Public Shared ReadOnly Property ContextMenuStrip1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenuStrip1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=971,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property ContextMenuStrip1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenuStrip1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Folgende Drucker verwenden noch den Treiber  ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DriverMultiplePrintersPart1() As String
            Get
                Return ResourceManager.GetString("DriverMultiplePrintersPart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Treiber kann nicht entfernt werden, ohne alle von dem Treiber abhängigen Drucker zu löschen. Möchten Sie alle abhängigen Drucker löschen? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DriverMultiplePrintersRemoveQuestion() As String
            Get
                Return ResourceManager.GetString("DriverMultiplePrintersRemoveQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=311, Height=22}.
        '''</summary>
        Public Shared ReadOnly Property DruckertreiberTreiberpaketEntfernenAdminToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckertreiberTreiberpaketEntfernenAdminToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker/Treiber/Treiberpaket entfernen (Admin)... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DruckertreiberTreiberpaketEntfernenAdminToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("DruckertreiberTreiberpaketEntfernenAdminToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=311, Height=22}.
        '''</summary>
        Public Shared ReadOnly Property DruckerTreiberTreiberpaketEntfernenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckerTreiberTreiberpaketEntfernenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker/Treiber/Treiberpaket entfernen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DruckerTreiberTreiberpaketEntfernenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("DruckerTreiberTreiberpaketEntfernenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ErrorLogStr() As String
            Get
                Return ResourceManager.GetString("ErrorLogStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker gefunden, bereit zum verbinden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ExactPrinterFoundPrinterSearchText() As String
            Get
                Return ResourceManager.GetString("ExactPrinterFoundPrinterSearchText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckereinstellungen erfolgreich exportiert. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ExportPrinterSettings() As String
            Get
                Return ResourceManager.GetString("ExportPrinterSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.AnchorStyles ähnlich wie Top, Bottom, Left, Right.
        '''</summary>
        Public Shared ReadOnly Property FlowLayoutPanel1_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("FlowLayoutPanel1.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property FlowLayoutPanel1_AutoScroll() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("FlowLayoutPanel1.AutoScroll", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=3,Y=3}.
        '''</summary>
        Public Shared ReadOnly Property FlowLayoutPanel1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("FlowLayoutPanel1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=415, Height=393}.
        '''</summary>
        Public Shared ReadOnly Property FlowLayoutPanel1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("FlowLayoutPanel1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 4.
        '''</summary>
        Public Shared ReadOnly Property FlowLayoutPanel1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("FlowLayoutPanel1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.AnchorStyles ähnlich wie Top, Bottom, Left, Right.
        '''</summary>
        Public Shared ReadOnly Property FlowLayoutPanel2_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("FlowLayoutPanel2.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property FlowLayoutPanel2_AutoScroll() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("FlowLayoutPanel2.AutoScroll", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=3,Y=3}.
        '''</summary>
        Public Shared ReadOnly Property FlowLayoutPanel2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("FlowLayoutPanel2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=415, Height=393}.
        '''</summary>
        Public Shared ReadOnly Property FlowLayoutPanel2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("FlowLayoutPanel2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 4.
        '''</summary>
        Public Shared ReadOnly Property FlowLayoutPanel2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("FlowLayoutPanel2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckereinstellungen erfolgreich importiert. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ImportPrinterSettings() As String
            Get
                Return ResourceManager.GetString("ImportPrinterSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=281,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property LoadAllLocalPrinters_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadAllLocalPrinters.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=116,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property LoadAllPrintersAsync_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadAllPrintersAsync.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=619,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property LocalPrinterChangeTimer_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("LocalPrinterChangeTimer.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=443,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property LocalPrinterIdleWorker_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("LocalPrinterIdleWorker.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property MetroButton1_Enabled() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton1.Enabled", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=334,Y=93}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=118, Height=29}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 3.
        '''</summary>
        Public Shared ReadOnly Property MetroButton1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker verbinden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroButton1_Text() As String
            Get
                Return ResourceManager.GetString("MetroButton1.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verbindet einen Drucker. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroButton1_ToolTip() As String
            Get
                Return ResourceManager.GetString("MetroButton1.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property MetroCheckBox1_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroCheckBox1.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=334,Y=127}.
        '''</summary>
        Public Shared ReadOnly Property MetroCheckBox1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroCheckBox1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=110, Height=15}.
        '''</summary>
        Public Shared ReadOnly Property MetroCheckBox1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroCheckBox1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 8.
        '''</summary>
        Public Shared ReadOnly Property MetroCheckBox1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroCheckBox1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Standarddrucker ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroCheckBox1_Text() As String
            Get
                Return ResourceManager.GetString("MetroCheckBox1.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aktivieren Sie diese Option, um den neuen Drucker auch als Standarddrucker festzulegen. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroCheckBox1_ToolTip() As String
            Get
                Return ResourceManager.GetString("MetroCheckBox1.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=23,Y=52}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=298, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 1.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie einen Druckernamen ein. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel1_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel1.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel2_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel2.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=49,Y=127}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=184, Height=15}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 5.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Suche nach Druckern im Netzwerk... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel2_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel2.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=24,Y=71}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel3_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel3.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=303, Height=15}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel3_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel3.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 12.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel3_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel3.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=3,Y=3}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel4_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel4.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=414, Height=386}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel4_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel4.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 4.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel4_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel4.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sie haben keine Drucker gespeichert. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel4_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel4.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=24,Y=94}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel5_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel5.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=302, Height=27}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel5_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel5.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 21.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel5_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel5.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bitte warten, Drucker werden geladen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel5_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel5.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.ContentAlignment ähnlich wie MiddleCenter.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel5_TextAlign() As System.Drawing.ContentAlignment
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel5.TextAlign", resourceCulture)
                Return CType(obj,System.Drawing.ContentAlignment)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.DockStyle ähnlich wie Fill.
        '''</summary>
        Public Shared ReadOnly Property MetroPanel1_Dock() As System.Windows.Forms.DockStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroPanel1.Dock", resourceCulture)
                Return CType(obj,System.Windows.Forms.DockStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=0,Y=0}.
        '''</summary>
        Public Shared ReadOnly Property MetroPanel1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroPanel1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=421, Height=399}.
        '''</summary>
        Public Shared ReadOnly Property MetroPanel1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroPanel1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 5.
        '''</summary>
        Public Shared ReadOnly Property MetroPanel1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroPanel1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.DockStyle ähnlich wie Fill.
        '''</summary>
        Public Shared ReadOnly Property MetroPanel2_Dock() As System.Windows.Forms.DockStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroPanel2.Dock", resourceCulture)
                Return CType(obj,System.Windows.Forms.DockStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=0,Y=0}.
        '''</summary>
        Public Shared ReadOnly Property MetroPanel2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroPanel2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=421, Height=399}.
        '''</summary>
        Public Shared ReadOnly Property MetroPanel2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroPanel2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 6.
        '''</summary>
        Public Shared ReadOnly Property MetroPanel2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroPanel2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=23,Y=124}.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=20, Height=20}.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 6.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.AnchorStyles ähnlich wie Top, Left, Right.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner2_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner2.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=150,Y=139}.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.Padding ähnlich wie {Left=0,Top=0,Right=0,Bottom=0}.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner2_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner2.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=120, Height=120}.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 3.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.AnchorStyles ähnlich wie Top, Bottom, Left, Right.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner3_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner3.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=0,Y=3}.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner3_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner3.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.Padding ähnlich wie {Left=0,Top=0,Right=0,Bottom=0}.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner3_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner3.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=417, Height=386}.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner3_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner3.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 3.
        '''</summary>
        Public Shared ReadOnly Property MetroProgressSpinner3_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroProgressSpinner3.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.AnchorStyles ähnlich wie Top, Bottom, Left, Right.
        '''</summary>
        Public Shared ReadOnly Property MetroTabControl1_Anchor() As System.Windows.Forms.AnchorStyles
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTabControl1.Anchor", resourceCulture)
                Return CType(obj,System.Windows.Forms.AnchorStyles)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=23,Y=164}.
        '''</summary>
        Public Shared ReadOnly Property MetroTabControl1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTabControl1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=429, Height=438}.
        '''</summary>
        Public Shared ReadOnly Property MetroTabControl1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTabControl1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 14.
        '''</summary>
        Public Shared ReadOnly Property MetroTabControl1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTabControl1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=4,Y=35}.
        '''</summary>
        Public Shared ReadOnly Property MetroTabPage1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTabPage1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=421, Height=399}.
        '''</summary>
        Public Shared ReadOnly Property MetroTabPage1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTabPage1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 0.
        '''</summary>
        Public Shared ReadOnly Property MetroTabPage1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTabPage1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vorhandene Drucker ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroTabPage1_Text() As String
            Get
                Return ResourceManager.GetString("MetroTabPage1.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=4,Y=35}.
        '''</summary>
        Public Shared ReadOnly Property MetroTabPage2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTabPage2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=421, Height=399}.
        '''</summary>
        Public Shared ReadOnly Property MetroTabPage2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTabPage2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 1.
        '''</summary>
        Public Shared ReadOnly Property MetroTabPage2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTabPage2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gespeicherte Drucker ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroTabPage2_Text() As String
            Get
                Return ResourceManager.GetString("MetroTabPage2.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=23,Y=93}.
        '''</summary>
        Public Shared ReadOnly Property MetroTextBox1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTextBox1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=304, Height=29}.
        '''</summary>
        Public Shared ReadOnly Property MetroTextBox1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTextBox1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 1.
        '''</summary>
        Public Shared ReadOnly Property MetroTextBox1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroTextBox1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Geben Sie hier den Namen des Druckers an. Wenn genügend Zeichen eingegeben worden sind, dann werden Vorschläge angezeigt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroTextBox1_ToolTip() As String
            Get
                Return ResourceManager.GetString("MetroTextBox1.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mehrere Ergebnisse. Bitte Suche verfeinern. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MultipleResultsPrinterSearchText() As String
            Get
                Return ResourceManager.GetString("MultipleResultsPrinterSearchText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Leider kein Drucker gefunden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property NoResultsPrinterSearchText() As String
            Get
                Return ResourceManager.GetString("NoResultsPrinterSearchText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=23,Y=124}.
        '''</summary>
        Public Shared ReadOnly Property PictureBox1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=20, Height=20}.
        '''</summary>
        Public Shared ReadOnly Property PictureBox1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.PictureBoxSizeMode ähnlich wie StretchImage.
        '''</summary>
        Public Shared ReadOnly Property PictureBox1_SizeMode() As System.Windows.Forms.PictureBoxSizeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.SizeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.PictureBoxSizeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 7.
        '''</summary>
        Public Shared ReadOnly Property PictureBox1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property PictureBox1_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=334,Y=43}.
        '''</summary>
        Public Shared ReadOnly Property PictureBox2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=118, Height=44}.
        '''</summary>
        Public Shared ReadOnly Property PictureBox2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.PictureBoxSizeMode ähnlich wie StretchImage.
        '''</summary>
        Public Shared ReadOnly Property PictureBox2_SizeMode() As System.Windows.Forms.PictureBoxSizeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox2.SizeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.PictureBoxSizeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 11.
        '''</summary>
        Public Shared ReadOnly Property PictureBox2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=298,Y=94}.
        '''</summary>
        Public Shared ReadOnly Property PictureBox3_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox3.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=28, Height=27}.
        '''</summary>
        Public Shared ReadOnly Property PictureBox3_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox3.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.PictureBoxSizeMode ähnlich wie StretchImage.
        '''</summary>
        Public Shared ReadOnly Property PictureBox3_SizeMode() As System.Windows.Forms.PictureBoxSizeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox3.SizeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.PictureBoxSizeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 16.
        '''</summary>
        Public Shared ReadOnly Property PictureBox3_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox3.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property PictureBox3_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox3.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  Drucker gefunden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PrinterCollectCountText() As String
            Get
                Return ResourceManager.GetString("PrinterCollectCountText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker geladen, bitte suchen. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PrinterCollectFinishedText() As String
            Get
                Return ResourceManager.GetString("PrinterCollectFinishedText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker nur teilweise geladen (Server nicht erreichbar). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PrinterCollectNotFinishedServerNotAv() As String
            Get
                Return ResourceManager.GetString("PrinterCollectNotFinishedServerNotAv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker nur teilweise geladen (Timeout). ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PrinterCollectNotFinishedTimeout() As String
            Get
                Return ResourceManager.GetString("PrinterCollectNotFinishedTimeout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bereit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PrinterReadyText() As String
            Get
                Return ResourceManager.GetString("PrinterReadyText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Möchten Sie wirklich den Drucker  ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RemovePrinterMessagePart1() As String
            Get
                Return ResourceManager.GetString("RemovePrinterMessagePart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  entfernen? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RemovePrinterMessagePart2() As String
            Get
                Return ResourceManager.GetString("RemovePrinterMessagePart2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=807,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property RestartPrinterService_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("RestartPrinterService.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=17,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property ToolTip2_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolTip2.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=311, Height=22}.
        '''</summary>
        Public Shared ReadOnly Property WindowsDruckverwaltungÖffnenAdminToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("WindowsDruckverwaltungÖffnenAdminToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Windows-Druckverwaltung öffnen (Admin)... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property WindowsDruckverwaltungÖffnenAdminToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("WindowsDruckverwaltungÖffnenAdminToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=311, Height=22}.
        '''</summary>
        Public Shared ReadOnly Property WindowsDruckverwaltungÖffnenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("WindowsDruckverwaltungÖffnenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Windows-Druckverwaltung öffnen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property WindowsDruckverwaltungÖffnenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("WindowsDruckverwaltungÖffnenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
