'Copyright (C) 2016-2019 Michael Kirgus
'This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
'This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
'You should have received a copy of the GNU General Public License along with this program; if not, see <https://www.gnu.org/licenses>.

'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class PrinterCtl
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConnectMyPrinter.NET.PrinterCtl", GetType(PrinterCtl).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property AlsStandarddruckerFestlegenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("AlsStandarddruckerFestlegenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Als Standarddrucker festlegen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AlsStandarddruckerFestlegenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("AlsStandarddruckerFestlegenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.FlatStyle ähnlich wie Flat.
        '''</summary>
        Public Shared ReadOnly Property Button1_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("Button1.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=367,Y=0}.
        '''</summary>
        Public Shared ReadOnly Property Button1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Button1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=22, Height=22}.
        '''</summary>
        Public Shared ReadOnly Property Button1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Button1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 12.
        '''</summary>
        Public Shared ReadOnly Property Button1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Button1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker entfernen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Button1_ToolTip() As String
            Get
                Return ResourceManager.GetString("Button1.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.FlatStyle ähnlich wie Flat.
        '''</summary>
        Public Shared ReadOnly Property Button2_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("Button2.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=367,Y=20}.
        '''</summary>
        Public Shared ReadOnly Property Button2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Button2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=22, Height=22}.
        '''</summary>
        Public Shared ReadOnly Property Button2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Button2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 11.
        '''</summary>
        Public Shared ReadOnly Property Button2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Button2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckereinstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Button2_ToolTip() As String
            Get
                Return ResourceManager.GetString("Button2.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=108,Y=190}.
        '''</summary>
        Public Shared ReadOnly Property ConfigFileLbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigFileLbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=85, Height=15}.
        '''</summary>
        Public Shared ReadOnly Property ConfigFileLbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigFileLbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 29.
        '''</summary>
        Public Shared ReadOnly Property ConfigFileLbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigFileLbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;ConfigFileLbl&gt; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ConfigFileLbl_Text() As String
            Get
                Return ResourceManager.GetString("ConfigFileLbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=345, Height=448}.
        '''</summary>
        Public Shared ReadOnly Property ContextMenuStrip1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenuStrip1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=17,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property ContextMenuStrip1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenuStrip1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=108,Y=172}.
        '''</summary>
        Public Shared ReadOnly Property DataFileLbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("DataFileLbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=74, Height=15}.
        '''</summary>
        Public Shared ReadOnly Property DataFileLbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DataFileLbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 27.
        '''</summary>
        Public Shared ReadOnly Property DataFileLbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("DataFileLbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;DatafileLbl&gt; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DataFileLbl_Text() As String
            Get
                Return ResourceManager.GetString("DataFileLbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property DescriptionLbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DescriptionLbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=107,Y=76}.
        '''</summary>
        Public Shared ReadOnly Property DescriptionLbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("DescriptionLbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=109, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property DescriptionLbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DescriptionLbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 20.
        '''</summary>
        Public Shared ReadOnly Property DescriptionLbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("DescriptionLbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;DescriptionLbl&gt; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DescriptionLbl_Text() As String
            Get
                Return ResourceManager.GetString("DescriptionLbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property DriverLbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverLbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=107,Y=98}.
        '''</summary>
        Public Shared ReadOnly Property DriverLbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverLbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=79, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property DriverLbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverLbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 21.
        '''</summary>
        Public Shared ReadOnly Property DriverLbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverLbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;DriverLbl&gt; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DriverLbl_Text() As String
            Get
                Return ResourceManager.GetString("DriverLbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=108,Y=208}.
        '''</summary>
        Public Shared ReadOnly Property DriverPathLbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverPathLbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=88, Height=15}.
        '''</summary>
        Public Shared ReadOnly Property DriverPathLbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverPathLbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 31.
        '''</summary>
        Public Shared ReadOnly Property DriverPathLbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverPathLbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;DriverPathLbl&gt; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DriverPathLbl_Text() As String
            Get
                Return ResourceManager.GetString("DriverPathLbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property DriverVersionLbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverVersionLbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=107,Y=121}.
        '''</summary>
        Public Shared ReadOnly Property DriverVersionLbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverVersionLbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=121, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property DriverVersionLbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverVersionLbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 22.
        '''</summary>
        Public Shared ReadOnly Property DriverVersionLbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("DriverVersionLbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;DriverVersionLbl&gt; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DriverVersionLbl_Text() As String
            Get
                Return ResourceManager.GetString("DriverVersionLbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property DruckereigenschaftenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckereigenschaftenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckereigenschaften ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DruckereigenschaftenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("DruckereigenschaftenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property DruckereigenschaftenToolStripMenuItem_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckereigenschaftenToolStripMenuItem.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property DruckereinstellungenExportierenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckereinstellungenExportierenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckereinstellungen exportieren... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DruckereinstellungenExportierenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("DruckereinstellungenExportierenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property DruckereinstellungenExportierenToolStripMenuItem_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckereinstellungenExportierenToolStripMenuItem.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property DruckereinstellungenImportierenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckereinstellungenImportierenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckereinstellungen importieren... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DruckereinstellungenImportierenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("DruckereinstellungenImportierenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property DruckereinstellungenImportierenToolStripMenuItem_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckereinstellungenImportierenToolStripMenuItem.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property DruckereinstellungenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckereinstellungenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckereinstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DruckereinstellungenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("DruckereinstellungenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property DruckereinstellungenToolStripMenuItem_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckereinstellungenToolStripMenuItem.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property DruckerEntfernenlokalToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckerEntfernenlokalToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker entfernen (lokal) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DruckerEntfernenlokalToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("DruckerEntfernenlokalToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property DruckerEntfernenlokalToolStripMenuItem_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckerEntfernenlokalToolStripMenuItem.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property DruckerEntfernenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckerEntfernenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker entfernen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DruckerEntfernenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("DruckerEntfernenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property DruckerImProfilSpeichernToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckerImProfilSpeichernToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker im Profil speichern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DruckerImProfilSpeichernToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("DruckerImProfilSpeichernToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property DruckerNeuInstallierenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckerNeuInstallierenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker neu installieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DruckerNeuInstallierenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("DruckerNeuInstallierenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property DruckerNeuInstallierenToolStripMenuItem_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("DruckerNeuInstallierenToolStripMenuItem.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property LocationLbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("LocationLbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=107,Y=53}.
        '''</summary>
        Public Shared ReadOnly Property LocationLbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("LocationLbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=93, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property LocationLbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("LocationLbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 19.
        '''</summary>
        Public Shared ReadOnly Property LocationLbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("LocationLbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;LocationLbl&gt; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property LocationLbl_Text() As String
            Get
                Return ResourceManager.GetString("LocationLbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=3,Y=235}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=183, Height=23}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 32.
        '''</summary>
        Public Shared ReadOnly Property MetroButton1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Testseite drucken ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroButton1_Text() As String
            Get
                Return ResourceManager.GetString("MetroButton1.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=192,Y=235}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=196, Height=23}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 33.
        '''</summary>
        Public Shared ReadOnly Property MetroButton2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckerwarteschlange öffnen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroButton2_Text() As String
            Get
                Return ResourceManager.GetString("MetroButton2.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=3,Y=261}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton3_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton3.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=183, Height=23}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton3_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton3.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 34.
        '''</summary>
        Public Shared ReadOnly Property MetroButton3_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton3.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckerwarteschlange leeren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroButton3_Text() As String
            Get
                Return ResourceManager.GetString("MetroButton3.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=192,Y=261}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton4_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton4.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=196, Height=23}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton4_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton4.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 35.
        '''</summary>
        Public Shared ReadOnly Property MetroButton4_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton4.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker + Treiber löschen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroButton4_Text() As String
            Get
                Return ResourceManager.GetString("MetroButton4.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=3,Y=287}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton5_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton5.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=183, Height=23}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton5_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton5.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 36.
        '''</summary>
        Public Shared ReadOnly Property MetroButton5_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton5.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucker neu installieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroButton5_Text() As String
            Get
                Return ResourceManager.GetString("MetroButton5.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=192,Y=287}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton6_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton6.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=196, Height=23}.
        '''</summary>
        Public Shared ReadOnly Property MetroButton6_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton6.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 37.
        '''</summary>
        Public Shared ReadOnly Property MetroButton6_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroButton6.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckerinformationen neu ermitteln ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroButton6_Text() As String
            Get
                Return ResourceManager.GetString("MetroButton6.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel10Lbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel10Lbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=4,Y=171}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel10Lbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel10Lbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=65, Height=15}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel10Lbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel10Lbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 26.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel10Lbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel10Lbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datendatei: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel10Lbl_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel10Lbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel12Lbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel12Lbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=4,Y=190}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel12Lbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel12Lbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=94, Height=15}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel12Lbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel12Lbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 28.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel12Lbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel12Lbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Konfigurationsfile: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel12Lbl_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel12Lbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel13Lbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel13Lbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=4,Y=208}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel13Lbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel13Lbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=66, Height=15}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel13Lbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel13Lbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 30.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel13Lbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel13Lbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Treiberpfad: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel13Lbl_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel13Lbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=44,Y=1}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel1Lbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel1Lbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=284, Height=23}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel1Lbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel1Lbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 1.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel1Lbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel1Lbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;PrinterName&gt; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel1Lbl_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel1Lbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckername ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel1Lbl_ToolTip() As String
            Get
                Return ResourceManager.GetString("MetroLabel1Lbl.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=48,Y=24}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel2Lbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel2Lbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=280, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel2Lbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel2Lbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 2.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel2Lbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel2Lbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;PrinterServer&gt; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel2Lbl_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel2Lbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name des Printservers, auf welchem dem Drucker angelegt ist. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel2Lbl_ToolTip() As String
            Get
                Return ResourceManager.GetString("MetroLabel2Lbl.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel3Lbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel3Lbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=2,Y=98}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel3Lbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel3Lbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=85, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel3Lbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel3Lbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 14.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel3Lbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel3Lbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Treibername: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel3Lbl_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel3Lbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel4Lbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel4Lbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=2,Y=121}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel4Lbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel4Lbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=94, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel4Lbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel4Lbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 15.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel4Lbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel4Lbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Treiberversion: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel4Lbl_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel4Lbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel5Lbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel5Lbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=2,Y=144}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel5Lbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel5Lbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=83, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel5Lbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel5Lbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 16.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel5Lbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel5Lbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gerätestatus: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel5Lbl_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel5Lbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel6Lbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel6Lbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=3,Y=53}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel6Lbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel6Lbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=63, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel6Lbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel6Lbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 17.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel6Lbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel6Lbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Standort: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel6Lbl_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel6Lbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel7Lbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel7Lbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=3,Y=76}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel7Lbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel7Lbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=90, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel7Lbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel7Lbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 18.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel7Lbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("MetroLabel7Lbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beschreibung: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property MetroLabel7Lbl_Text() As String
            Get
                Return ResourceManager.GetString("MetroLabel7Lbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckereinstellungen (*.dat)|*.dat|Alle Dateien|*.* ähnelt.
        '''</summary>
        Public Shared ReadOnly Property OpenFileDialog1_Filter() As String
            Get
                Return ResourceManager.GetString("OpenFileDialog1.Filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=410,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property OpenFileDialog1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFileDialog1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=3,Y=4}.
        '''</summary>
        Public Shared ReadOnly Property PictureBox1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=35, Height=35}.
        '''</summary>
        Public Shared ReadOnly Property PictureBox1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.PictureBoxSizeMode ähnlich wie CenterImage.
        '''</summary>
        Public Shared ReadOnly Property PictureBox1_SizeMode() As System.Windows.Forms.PictureBoxSizeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.SizeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.PictureBoxSizeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 0.
        '''</summary>
        Public Shared ReadOnly Property PictureBox1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=336,Y=7}.
        '''</summary>
        Public Shared ReadOnly Property PictureBox2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=28, Height=28}.
        '''</summary>
        Public Shared ReadOnly Property PictureBox2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Windows.Forms.PictureBoxSizeMode ähnlich wie StretchImage.
        '''</summary>
        Public Shared ReadOnly Property PictureBox2_SizeMode() As System.Windows.Forms.PictureBoxSizeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox2.SizeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.PictureBoxSizeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 13.
        '''</summary>
        Public Shared ReadOnly Property PictureBox2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erweitern/Minimieren des Elements. Blendet weitere Informationen und Aktionen ein, bzw. blendet diese aus. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PictureBox2_ToolTip() As String
            Get
                Return ResourceManager.GetString("PictureBox2.ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property ProfildateiErstellenverbindenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfildateiErstellenverbindenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Profildatei erstellen (verbinden)... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ProfildateiErstellenverbindenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("ProfildateiErstellenverbindenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property ProfildateiErstellenverbindenToolStripMenuItem_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfildateiErstellenverbindenToolStripMenuItem.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property ProfildateioErstellenentfernenUndVerbindenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfildateioErstellenentfernenUndVerbindenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Profildatei erstellen (entfernen und verbinden)... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ProfildateioErstellenentfernenUndVerbindenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("ProfildateioErstellenentfernenUndVerbindenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property ProfildateioErstellenentfernenUndVerbindenToolStripMenuItem_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfildateioErstellenentfernenUndVerbindenToolStripMenuItem.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property ProfildateiVersendenentfernenUndVerbindenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfildateiVersendenentfernenUndVerbindenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Profildatei versenden (entfernen und verbinden)... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ProfildateiVersendenentfernenUndVerbindenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("ProfildateiVersendenentfernenUndVerbindenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property ProfildateiVersendenentfernenUndVerbindenToolStripMenuItem_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfildateiVersendenentfernenUndVerbindenToolStripMenuItem.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property ProfildateiVersendenverbindenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfildateiVersendenverbindenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Profildatei versenden (verbinden)... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ProfildateiVersendenverbindenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("ProfildateiVersendenverbindenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property ProfildateiVersendenverbindenToolStripMenuItem_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfildateiVersendenverbindenToolStripMenuItem.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druckereinstellungen (*.dat)|*.dat|Alle Dateien|*.* ähnelt.
        '''</summary>
        Public Shared ReadOnly Property SaveFileDialog1_Filter() As String
            Get
                Return ResourceManager.GetString("SaveFileDialog1.Filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=273,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property SaveFileDialog1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveFileDialog1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Profildatei|*.prpr ähnelt.
        '''</summary>
        Public Shared ReadOnly Property SaveFileDialog2_Filter() As String
            Get
                Return ResourceManager.GetString("SaveFileDialog2.Filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=552,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property SaveFileDialog2_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveFileDialog2.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=344, Height=30}.
        '''</summary>
        Public Shared ReadOnly Property StandardeinstellungenLöschenToolStripMenuItem_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("StandardeinstellungenLöschenToolStripMenuItem.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Standardeinstellungen löschen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property StandardeinstellungenLöschenToolStripMenuItem_Text() As String
            Get
                Return ResourceManager.GetString("StandardeinstellungenLöschenToolStripMenuItem.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        '''</summary>
        Public Shared ReadOnly Property StateLbl_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("StateLbl.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=107,Y=144}.
        '''</summary>
        Public Shared ReadOnly Property StateLbl_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("StateLbl.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=73, Height=19}.
        '''</summary>
        Public Shared ReadOnly Property StateLbl_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("StateLbl.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Int32 ähnlich wie 23.
        '''</summary>
        Public Shared ReadOnly Property StateLbl_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("StateLbl.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;StateLbl&gt; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property StateLbl_Text() As String
            Get
                Return ResourceManager.GetString("StateLbl.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=341, Height=6}.
        '''</summary>
        Public Shared ReadOnly Property ToolStripSeparator1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolStripSeparator1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=341, Height=6}.
        '''</summary>
        Public Shared ReadOnly Property ToolStripSeparator2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolStripSeparator2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=341, Height=6}.
        '''</summary>
        Public Shared ReadOnly Property ToolStripSeparator3_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolStripSeparator3.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property ToolStripSeparator3_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolStripSeparator3.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Size ähnlich wie {Width=341, Height=6}.
        '''</summary>
        Public Shared ReadOnly Property ToolStripSeparator4_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolStripSeparator4.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        '''</summary>
        Public Shared ReadOnly Property ToolStripSeparator4_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolStripSeparator4.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=174,Y=17}.
        '''</summary>
        Public Shared ReadOnly Property ToolTip1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolTip1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
    End Class
End Namespace
