'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TranslatedStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConnectMyPrinter.NET.TranslatedStrings", GetType(TranslatedStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Folgender Drucker ist auf mehr als einem Printserver angelegt. Name des Druckers:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DriverMultiplePrintersPart1() As String
            Get
                Return ResourceManager.GetString("DriverMultiplePrintersPart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Treiber wird von mehreren Druckern verwendet. Möchten Sie alle Drucker, welche diesen Treiber verwenden entfernen? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DriverMultiplePrintersRemoveQuestion() As String
            Get
                Return ResourceManager.GetString("DriverMultiplePrintersRemoveQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Druckereinstellungen wurden erfolgreich exportiert. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportPrinterSettings() As String
            Get
                Return ResourceManager.GetString("ExportPrinterSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Druckereinstellungen wurden erfolgreich importiert. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ImportPrinterSettings() As String
            Get
                Return ResourceManager.GetString("ImportPrinterSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  wirklich entfernen? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RemovePrinterMessagePart1() As String
            Get
                Return ResourceManager.GetString("RemovePrinterMessagePart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Möchten Sie den Drucker  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RemovePrinterMessagePart2() As String
            Get
                Return ResourceManager.GetString("RemovePrinterMessagePart2", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
